services:
  certbot:
    image: certbot/dns-duckdns
    container_name: certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - ./config:/opt/duckdns
      - ./config/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  certbot-conf:
    external: true
