services:
  certbot:
    image: certbot:aws-custom
    container_name: certbot
    volumes:
      - certbot-certs:/etc/letsencrypt
      - ./config:/opt/duckdns
      - ./config/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  certbot-certs:
    external: true
